### ISSUE TITLE
Set List and Map child items by key

### ISSUE THREAD

**Issue by zegl** [zegl/Gus#34]
This is currently supported in Map with `Map.Set(key, value)`.

Although, something like this would be optimal:

```dart
map["key"] = "value"
list[1337] = "value"
```

**Comment by isergey** [comment]
I think is map.set('key', value)  and map.get(key, default=null) better then [ ] operator.
What we'll do if key don't exist? Default value is good choice.

**Comment by zegl** [comment]
You might be correct, at least it is far more easily to implement your alternative.

See:
https://github.com/zegl/Gus/commit/1eb62ed832ff00151f4c83f67e71eb8e68d679a3
https://github.com/zegl/Gus/commit/a8beffb78f64330f5f25fbbfb734f94618a19773
